# Optimización de Hiperparámetros VCP con Optuna

Busca la mejor configuración de ~12 parámetros del detector VCP usando TPE (Tree-structured Parzen Estimator).

**Prerequisitos:**
```bash
pip install optuna plotly mlflow
```

## 1. Setup e imports

In [2]:
import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import optuna

optuna.logging.set_verbosity(optuna.logging.INFO)
warnings.filterwarnings("ignore", category=FutureWarning, module="mlflow")

project_root = Path.cwd().parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from autoresearch import (
    SwingCache,
    filter_tickers_by_start_date,
    find_common_period,
    get_ticker_info,
    load_universe,
    build_objective_function,
    create_study,
    run_backtest_for_params,
    compute_objective_score,
    study_to_dataframe,
    top_trials_summary,
    param_importance,
    reconstruct_pipeline_params,
    trades_to_dataframe,
    MLflowOptunaLogger,
    DEFAULT_RISK_PARAMS,
)

pd.set_option("display.float_format", "{:.4f}".format)
DATA_DIR = project_root / "data" / "csv"
print(f"Project root: {project_root}")
print(f"Data dir: {DATA_DIR}")
print("Imports OK")

Project root: /home/gdelarosa/proyectos/deteccion-vcp
Data dir: /home/gdelarosa/proyectos/deteccion-vcp/data/csv
Imports OK

## 2. Cargar y filtrar universo de tickers

In [3]:
ticker_info = get_ticker_info(DATA_DIR)
display(ticker_info)

       start_date   end_date  n_bars
ticker
AAPL   2015-01-02 2026-04-08    2832
AMZN   2015-01-02 2026-04-08    2832
AVGO   2015-01-02 2026-04-08    2832
BRK.B  2015-01-02 2026-04-10    2834
COIN   2021-04-14 2026-04-10    1254
GLD    2015-01-02 2026-04-10    2834
GOOGL  2015-01-02 2026-04-08    2832
HOOD   2021-07-29 2026-04-10    1180
IWM    2015-01-02 2026-04-10    2834
JPM    2015-01-02 2026-04-10    2834
META   2021-06-30 2026-04-08    1108
MSFT   2015-01-02 2026-04-08    2832
NVDA   2015-01-02 2026-04-08    2832
PLTR   2020-09-30 2026-04-10    1388
QLD    2015-01-02 2026-04-08    2832
QQQ    2015-01-02 2026-04-08    2832
SLV    2015-01-02 2026-04-10    2834
SOFI   2021-06-01 2026-04-10    1221
SPY    2015-01-02 2026-04-08    2832
SQQQ   2015-01-02 2026-04-08    2832
TIL    2015-05-27 2026-04-10    1814
TLT    2015-01-02 2026-04-08    2832
TQQQ   2015-01-02 2026-04-08    2832

In [4]:
opt_tickers, oos_tickers = filter_tickers_by_start_date(
    DATA_DIR, max_start_date="2015-12-31", exclude_tickers=["META"]
)
print(f"Optimization set ({len(opt_tickers)}): {opt_tickers}")
print(f"Out-of-sample set ({len(oos_tickers)}): {oos_tickers}")

Optimization set (18): ['AAPL', 'AMZN', 'AVGO', 'BRK.B', 'GLD', 'GOOGL', 'IWM', 'JPM', 'MSFT', 'NVDA', 'QLD', 'QQQ', 'SLV', 'SPY', 'SQQQ', 'TIL', 'TLT', 'TQQQ']
Out-of-sample set (4): ['COIN', 'HOOD', 'PLTR', 'SOFI']

In [5]:
universe = load_universe(opt_tickers, DATA_DIR)
common_start, common_end = find_common_period(universe)
print(f"Universe: {len(universe)} tickers")
print(f"Common period: {common_start.date()} to {common_end.date()}")
print(f"Bars per ticker: {[len(df) for df in universe.values()]}")

Universe: 18 tickers
Common period: 2015-05-27 to 2026-04-08
Bars per ticker: [2832, 2832, 2832, 2834, 2834, 2832, 2834, 2834, 2832, 2832, 2832, 2832, 2834, 2832, 2832, 1814, 2832, 2832]

## 3. Baseline: parámetros del experimento original

Corremos el pipeline con los parámetros conocidos (`volume_ratio_threshold=1.5`) como referencia.

In [6]:
from models.configs import ATRZigZagConfig

BASELINE_PARAMS = {
    "swing_config": ATRZigZagConfig(atr_length=14, atr_mult=2.0, use_close_only=False),
    "sequence_params": {
        "method": "tolerance",
        "min_contractions": 2,
        "max_contractions": 6,
        "lookback_bars": 126,
        "tolerance": 0.10,
        "max_depth_pct": 0.35,
        "min_total_reduction": 0.80,
        "max_gap_between_contractions_days": None,
    },
    "compression_params": {
        "method": "ratio",
        "atr_period": 14,
        "ratio_threshold": 0.85,
    },
    "volume_contraction_params": {
        "method": "ratio",
        "volume_column": "volume",
        "ratio_threshold": 0.85,
    },
    "breakout_params": {
        "volume_method": "ratio",
        "volume_ratio_threshold": 1.5,
        "volume_lookback_days": 50,
        "require_volume_confirmation": True,
    },
    "grouping_params": {"max_gap_days": 30},
    "risk_params": dict(DEFAULT_RISK_PARAMS),
}

In [7]:
baseline_result = run_backtest_for_params(universe, BASELINE_PARAMS)
baseline_metrics = baseline_result["metrics"]
baseline_score = compute_objective_score(baseline_metrics)

print("=== BASELINE ===")
print(f"  n_trades:       {baseline_metrics['n_trades']}")
print(f"  expectancy_r:   {baseline_metrics['expectancy_r']:+.4f}")
print(f"  win_rate:       {baseline_metrics['win_rate']:.1%}")
print(f"  profit_factor:  {baseline_metrics['profit_factor']:.2f}")
print(f"  score (Opt C):  {baseline_score:+.4f}")
print(f"\n  Trades per ticker:")
for ticker, n in sorted(baseline_metrics["trades_per_ticker"].items()):
    print(f"    {ticker}: {n}")

=== BASELINE ===
  n_trades:       78
  expectancy_r:   +0.3058
  win_rate:       46.2%
  profit_factor:  1.62
  score (Opt C):  +2.7004

  Trades per ticker:
    AAPL: 6
    AMZN: 14
    AVGO: 6
    BRK.B: 3
    GLD: 4
    GOOGL: 10
    IWM: 2
    JPM: 6
    MSFT: 5
    NVDA: 2
    QLD: 2
    QQQ: 2
    SLV: 4
    SPY: 4
    SQQQ: 2
    TIL: 1
    TLT: 3
    TQQQ: 2

## 4. Configurar y correr optimización (100 trials)

TPESampler con `multivariate=True`, 20 startup trials random, seed=42.
Cada trial corre el pipeline completo sobre los 18 tickers. SwingCache
evita recomputar pasos 1-2 cuando el swing_config se repite entre trials.

In [8]:
N_TRIALS = 50
STUDY_NAME = "vcp_optuna_phase1"
MLFLOW_EXPERIMENT = "autoresearch_vcp_phase1"

In [9]:
import multiprocessing

# Paralelizacion: usar 8 de los 16 cores (dejar margen para sistema + cache contention)
N_JOBS = 1

print(f"CPU cores disponibles: {multiprocessing.cpu_count()}")
print(f"Trials en paralelo: {N_JOBS}")
print(f"Total trials: {N_TRIALS}\n")

cache = SwingCache()
objective = build_objective_function(universe, cache=cache)
study = create_study(study_name=STUDY_NAME, n_startup_trials=20, seed=42)
logger = MLflowOptunaLogger(experiment_name=MLFLOW_EXPERIMENT)

with logger.parent_run(study_name=STUDY_NAME, tags={"n_tickers": str(len(universe)), "n_jobs": str(N_JOBS)}):
    study.optimize(
        objective, 
        n_trials=N_TRIALS, 
        n_jobs=N_JOBS,
        callbacks=[logger.optuna_callback],
        show_progress_bar=True,
    )
    logger.log_study_summary(study, n_tickers=len(universe))

print(f"\nOptimización completada: {len(study.trials)} trials")
print(f"Best score: {study.best_value:+.4f} (trial #{study.best_trial.number})")
print(f"Cache stats: {cache.stats()}")

/home/gdelarosa/proyectos/deteccion-vcp/autoresearch/objective.py:73: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  sampler = optuna.samplers.TPESampler(
[I 2026-05-06 20:04:55,226] A new study created in memory with name: vcp_optuna_phase1

CPU cores disponibles: 16
Trials en paralelo: 1
Total trials: 50

Best trial: 0. Best value: 3.05306:   2%|▏         | 1/50 [00:28<23:21, 28.61s/it]

[I 2026-05-06 20:05:23,902] Trial 0 finished with value: 3.0530573444124185 and parameters: {'atr_length': 15, 'atr_mult': 3.5, 'min_contractions': 3, 'max_contractions': 6, 'lookback_bars': 90, 'tolerance': 0.07500000000000001, 'max_depth_pct': 0.26161672243363987, 'min_total_reduction': 0.8665440364437338, 'compression_threshold': 0.8502787529358021, 'vol_contraction_threshold': 0.891614515559209, 'volume_ratio_threshold': 1.3144091460070617, 'max_gap_days': 40}. Best is trial 0 with value: 3.0530573444124185.

Best trial: 0. Best value: 3.05306:   4%|▍         | 2/50 [05:33<2:32:58, 191.22s/it]

[I 2026-05-06 20:10:28,965] Trial 1 finished with value: 2.7230177006082226 and parameters: {'atr_length': 23, 'atr_mult': 1.75, 'min_contractions': 2, 'max_contractions': 5, 'lookback_bars': 100, 'tolerance': 0.125, 'max_depth_pct': 0.3363890037284232, 'min_total_reduction': 0.7228072850495105, 'compression_threshold': 0.8529632236805949, 'vol_contraction_threshold': 0.7778987721304084, 'volume_ratio_threshold': 1.5045012539746527, 'max_gap_days': 27}. Best is trial 0 with value: 3.0530573444124185.

Best trial: 0. Best value: 3.05306:   6%|▌         | 3/50 [07:42<2:07:24, 162.66s/it]

[I 2026-05-06 20:12:37,635] Trial 2 finished with value: 0.9533847865881367 and parameters: {'atr_length': 17, 'atr_mult': 3.25, 'min_contractions': 2, 'max_contractions': 6, 'lookback_bars': 120, 'tolerance': 0.05, 'max_depth_pct': 0.3715089703802877, 'min_total_reduction': 0.6926310309218229, 'compression_threshold': 0.7162628982463198, 'vol_contraction_threshold': 0.9397771074506667, 'volume_ratio_threshold': 1.9759424231521916, 'max_gap_days': 36}. Best is trial 0 with value: 3.0530573444124185.

Best trial: 0. Best value: 3.05306:   8%|▊         | 4/50 [09:51<1:54:33, 149.43s/it]

[I 2026-05-06 20:14:46,780] Trial 3 finished with value: 1.6555280190810775 and parameters: {'atr_length': 14, 'atr_mult': 1.5, 'min_contractions': 3, 'max_contractions': 6, 'lookback_bars': 80, 'tolerance': 0.125, 'max_depth_pct': 0.2568777042230437, 'min_total_reduction': 0.8773301005196955, 'compression_threshold': 0.7646949954000042, 'vol_contraction_threshold': 0.8825044568707964, 'volume_ratio_threshold': 1.5181977532625877, 'max_gap_days': 30}. Best is trial 0 with value: 3.0530573444124185.

Best trial: 0. Best value: 3.05306:  10%|█         | 5/50 [12:41<1:57:42, 156.94s/it]

[I 2026-05-06 20:17:37,047] Trial 4 finished with value: 0.002278762464268917 and parameters: {'atr_length': 18, 'atr_mult': 1.75, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 140, 'tolerance': 0.2, 'max_depth_pct': 0.369579995762217, 'min_total_reduction': 0.8804685587557792, 'compression_threshold': 0.7221231255129799, 'vol_contraction_threshold': 0.789196572483829, 'volume_ratio_threshold': 1.3316591022373767, 'max_gap_days': 26}. Best is trial 0 with value: 3.0530573444124185.

Best trial: 0. Best value: 3.05306:  12%|█▏        | 6/50 [14:42<1:46:05, 144.68s/it]

[I 2026-05-06 20:19:37,921] Trial 5 finished with value: 2.065713006779461 and parameters: {'atr_length': 16, 'atr_mult': 2.0, 'min_contractions': 3, 'max_contractions': 6, 'lookback_bars': 90, 'tolerance': 0.125, 'max_depth_pct': 0.27818484499495255, 'min_total_reduction': 0.8505492451885099, 'compression_threshold': 0.7186376609199426, 'vol_contraction_threshold': 0.9473773873201035, 'volume_ratio_threshold': 1.8405713385076603, 'max_gap_days': 24}. Best is trial 0 with value: 3.0530573444124185.

Best trial: 6. Best value: 3.3287:  14%|█▍        | 7/50 [15:44<1:24:14, 117.54s/it]

[I 2026-05-06 20:20:39,589] Trial 6 finished with value: 3.3286963277018153 and parameters: {'atr_length': 10, 'atr_mult': 3.25, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 130, 'tolerance': 0.05, 'max_depth_pct': 0.32169314570885454, 'min_total_reduction': 0.6789672648812825, 'compression_threshold': 0.9157758564688984, 'vol_contraction_threshold': 0.8746596253655116, 'volume_ratio_threshold': 1.5316286173968545, 'max_gap_days': 21}. Best is trial 6 with value: 3.3286963277018153.

Best trial: 6. Best value: 3.3287:  16%|█▌        | 8/50 [17:53<1:24:47, 121.13s/it]

[I 2026-05-06 20:22:48,409] Trial 7 finished with value: 1.1287411871070692 and parameters: {'atr_length': 14, 'atr_mult': 2.0, 'min_contractions': 3, 'max_contractions': 6, 'lookback_bars': 140, 'tolerance': 0.125, 'max_depth_pct': 0.27391884918766035, 'min_total_reduction': 0.8283111968057488, 'compression_threshold': 0.8901962621542243, 'vol_contraction_threshold': 0.8622554395138993, 'volume_ratio_threshold': 1.8396770259681927, 'max_gap_days': 30}. Best is trial 6 with value: 3.3286963277018153.

Best trial: 6. Best value: 3.3287:  18%|█▊        | 9/50 [21:27<1:42:38, 150.20s/it]

[I 2026-05-06 20:26:22,514] Trial 8 finished with value: 1.0833273746945549 and parameters: {'atr_length': 18, 'atr_mult': 2.25, 'min_contractions': 2, 'max_contractions': 5, 'lookback_bars': 80, 'tolerance': 0.15000000000000002, 'max_depth_pct': 0.3128711962152653, 'min_total_reduction': 0.7771426727911757, 'compression_threshold': 0.9268916184815232, 'vol_contraction_threshold': 0.7998584458297749, 'volume_ratio_threshold': 1.5872680461249409, 'max_gap_days': 35}. Best is trial 6 with value: 3.3286963277018153.

Best trial: 6. Best value: 3.3287:  20%|██        | 10/50 [26:01<2:05:43, 188.58s/it]

[I 2026-05-06 20:30:57,045] Trial 9 finished with value: 1.4689702603113015 and parameters: {'atr_length': 13, 'atr_mult': 1.5, 'min_contractions': 2, 'max_contractions': 5, 'lookback_bars': 140, 'tolerance': 0.175, 'max_depth_pct': 0.37668075130208467, 'min_total_reduction': 0.8678651475469294, 'compression_threshold': 0.9009180192247785, 'vol_contraction_threshold': 0.7873140117772072, 'volume_ratio_threshold': 1.9247912989429845, 'max_gap_days': 31}. Best is trial 6 with value: 3.3286963277018153.

Best trial: 6. Best value: 3.3287:  22%|██▏       | 11/50 [27:58<1:48:19, 166.67s/it]

[I 2026-05-06 20:32:54,017] Trial 10 finished with value: 0.9727206236775245 and parameters: {'atr_length': 22, 'atr_mult': 3.5, 'min_contractions': 2, 'max_contractions': 5, 'lookback_bars': 90, 'tolerance': 0.1, 'max_depth_pct': 0.41360295318449863, 'min_total_reduction': 0.8651826458140859, 'compression_threshold': 0.7017380326327977, 'vol_contraction_threshold': 0.8521494605155131, 'volume_ratio_threshold': 1.5921877022041453, 'max_gap_days': 24}. Best is trial 6 with value: 3.3286963277018153.

Best trial: 6. Best value: 3.3287:  24%|██▍       | 12/50 [30:07<1:38:16, 155.17s/it]

[I 2026-05-06 20:35:02,889] Trial 11 finished with value: -1.8650528561954653 and parameters: {'atr_length': 11, 'atr_mult': 2.25, 'min_contractions': 3, 'max_contractions': 5, 'lookback_bars': 110, 'tolerance': 0.15000000000000002, 'max_depth_pct': 0.3227259204758588, 'min_total_reduction': 0.8929455206802401, 'compression_threshold': 0.9406118237355278, 'vol_contraction_threshold': 0.8003564591650728, 'volume_ratio_threshold': 1.6480739541246698, 'max_gap_days': 26}. Best is trial 6 with value: 3.3286963277018153.

Best trial: 6. Best value: 3.3287:  26%|██▌       | 13/50 [31:56<1:27:02, 141.15s/it]

[I 2026-05-06 20:36:51,796] Trial 12 finished with value: -1.374827262154932 and parameters: {'atr_length': 14, 'atr_mult': 1.5, 'min_contractions': 3, 'max_contractions': 6, 'lookback_bars': 80, 'tolerance': 0.07500000000000001, 'max_depth_pct': 0.43165317719333074, 'min_total_reduction': 0.7098904726667431, 'compression_threshold': 0.7362237180228057, 'vol_contraction_threshold': 0.8478905520555126, 'volume_ratio_threshold': 1.9899553178774205, 'max_gap_days': 25}. Best is trial 6 with value: 3.3286963277018153.

Best trial: 6. Best value: 3.3287:  28%|██▊       | 14/50 [34:49<1:30:28, 150.78s/it]

[I 2026-05-06 20:39:44,810] Trial 13 finished with value: 1.6381422697260077 and parameters: {'atr_length': 20, 'atr_mult': 3.0, 'min_contractions': 2, 'max_contractions': 7, 'lookback_bars': 100, 'tolerance': 0.15000000000000002, 'max_depth_pct': 0.37670594215217895, 'min_total_reduction': 0.7839436710186897, 'compression_threshold': 0.722572442513602, 'vol_contraction_threshold': 0.9170604991178476, 'volume_ratio_threshold': 1.524546045480215, 'max_gap_days': 23}. Best is trial 6 with value: 3.3286963277018153.

Best trial: 6. Best value: 3.3287:  30%|███       | 15/50 [36:15<1:16:30, 131.16s/it]

[I 2026-05-06 20:41:10,493] Trial 14 finished with value: 0.8615763345200689 and parameters: {'atr_length': 10, 'atr_mult': 2.75, 'min_contractions': 3, 'max_contractions': 5, 'lookback_bars': 110, 'tolerance': 0.07500000000000001, 'max_depth_pct': 0.37903455808189, 'min_total_reduction': 0.6935916072512479, 'compression_threshold': 0.8727344345256165, 'vol_contraction_threshold': 0.8273470692601075, 'volume_ratio_threshold': 1.9557109921157143, 'max_gap_days': 22}. Best is trial 6 with value: 3.3286963277018153.

Best trial: 6. Best value: 3.3287:  32%|███▏      | 16/50 [38:52<1:18:51, 139.16s/it]

[I 2026-05-06 20:43:48,248] Trial 15 finished with value: 2.307146371793467 and parameters: {'atr_length': 15, 'atr_mult': 1.75, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 90, 'tolerance': 0.15000000000000002, 'max_depth_pct': 0.41344444004024317, 'min_total_reduction': 0.7888002028998656, 'compression_threshold': 0.8324126445890015, 'vol_contraction_threshold': 0.7983704581800903, 'volume_ratio_threshold': 1.3651719374641296, 'max_gap_days': 38}. Best is trial 6 with value: 3.3286963277018153.

Best trial: 6. Best value: 3.3287:  34%|███▍      | 17/50 [43:23<1:38:14, 178.62s/it]

[I 2026-05-06 20:48:18,631] Trial 16 finished with value: 1.7825842768932545 and parameters: {'atr_length': 24, 'atr_mult': 2.75, 'min_contractions': 2, 'max_contractions': 6, 'lookback_bars': 130, 'tolerance': 0.2, 'max_depth_pct': 0.42741728485302344, 'min_total_reduction': 0.844968886464406, 'compression_threshold': 0.8605079115385719, 'vol_contraction_threshold': 0.7668279929990097, 'volume_ratio_threshold': 1.4131400998662296, 'max_gap_days': 38}. Best is trial 6 with value: 3.3286963277018153.

Best trial: 6. Best value: 3.3287:  36%|███▌      | 18/50 [47:39<1:47:44, 202.02s/it]

[I 2026-05-06 20:52:35,122] Trial 17 finished with value: 1.9245933478688004 and parameters: {'atr_length': 19, 'atr_mult': 1.5, 'min_contractions': 2, 'max_contractions': 6, 'lookback_bars': 80, 'tolerance': 0.07500000000000001, 'max_depth_pct': 0.3597467578733172, 'min_total_reduction': 0.8229737994231734, 'compression_threshold': 0.8629903148756501, 'vol_contraction_threshold': 0.7948538618921119, 'volume_ratio_threshold': 1.7985254549432752, 'max_gap_days': 24}. Best is trial 6 with value: 3.3286963277018153.

Best trial: 6. Best value: 3.3287:  38%|███▊      | 19/50 [48:58<1:25:10, 164.87s/it]

[I 2026-05-06 20:53:53,451] Trial 18 finished with value: 1.039307358452728 and parameters: {'atr_length': 15, 'atr_mult': 3.0, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 120, 'tolerance': 0.125, 'max_depth_pct': 0.2687349535656185, 'min_total_reduction': 0.7419289507648584, 'compression_threshold': 0.7663005919204313, 'vol_contraction_threshold': 0.7987979286758167, 'volume_ratio_threshold': 1.9811073883267118, 'max_gap_days': 28}. Best is trial 6 with value: 3.3286963277018153.

Best trial: 6. Best value: 3.3287:  40%|████      | 20/50 [50:53<1:14:59, 149.98s/it]

[I 2026-05-06 20:55:48,713] Trial 19 finished with value: 0.9728340621673351 and parameters: {'atr_length': 24, 'atr_mult': 2.75, 'min_contractions': 3, 'max_contractions': 6, 'lookback_bars': 120, 'tolerance': 0.125, 'max_depth_pct': 0.2890485975596089, 'min_total_reduction': 0.8306130288153764, 'compression_threshold': 0.7701930906102139, 'vol_contraction_threshold': 0.7548631932862908, 'volume_ratio_threshold': 1.7518306071350174, 'max_gap_days': 23}. Best is trial 6 with value: 3.3286963277018153.

Best trial: 6. Best value: 3.3287:  42%|████▏     | 21/50 [51:27<55:40, 115.19s/it]

[I 2026-05-06 20:56:22,792] Trial 20 finished with value: 3.1527064033644856 and parameters: {'atr_length': 15, 'atr_mult': 3.0, 'min_contractions': 3, 'max_contractions': 6, 'lookback_bars': 80, 'tolerance': 0.1, 'max_depth_pct': 0.31115130042599726, 'min_total_reduction': 0.8431143177835801, 'compression_threshold': 0.8669618610171514, 'vol_contraction_threshold': 0.9177779025068221, 'volume_ratio_threshold': 1.465981638027349, 'max_gap_days': 40}. Best is trial 6 with value: 3.3286963277018153.

Best trial: 6. Best value: 3.3287:  44%|████▍     | 22/50 [51:56<41:41, 89.34s/it]

[I 2026-05-06 20:56:51,854] Trial 21 finished with value: 3.288481548168099 and parameters: {'atr_length': 15, 'atr_mult': 3.25, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 90, 'tolerance': 0.05, 'max_depth_pct': 0.29311954021084663, 'min_total_reduction': 0.8558894181412404, 'compression_threshold': 0.8903385596612188, 'vol_contraction_threshold': 0.9450686733639995, 'volume_ratio_threshold': 1.3911836506838002, 'max_gap_days': 40}. Best is trial 6 with value: 3.3286963277018153.

Best trial: 6. Best value: 3.3287:  46%|████▌     | 23/50 [52:29<32:31, 72.27s/it]

[I 2026-05-06 20:57:24,315] Trial 22 finished with value: 1.1669584868604532 and parameters: {'atr_length': 10, 'atr_mult': 3.5, 'min_contractions': 3, 'max_contractions': 6, 'lookback_bars': 120, 'tolerance': 0.05, 'max_depth_pct': 0.28962756733089634, 'min_total_reduction': 0.6538127828740695, 'compression_threshold': 0.8972070653945373, 'vol_contraction_threshold': 0.8654949397367535, 'volume_ratio_threshold': 1.5860208112730672, 'max_gap_days': 23}. Best is trial 6 with value: 3.3286963277018153.

Best trial: 6. Best value: 3.3287:  48%|████▊     | 24/50 [53:57<33:26, 77.15s/it]

[I 2026-05-06 20:58:52,859] Trial 23 finished with value: 0.1684144934874916 and parameters: {'atr_length': 12, 'atr_mult': 3.0, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 130, 'tolerance': 0.05, 'max_depth_pct': 0.4160374234562443, 'min_total_reduction': 0.7364335633367999, 'compression_threshold': 0.8608546181489876, 'vol_contraction_threshold': 0.849677597635274, 'volume_ratio_threshold': 1.4378976400950554, 'max_gap_days': 21}. Best is trial 6 with value: 3.3286963277018153.

Best trial: 6. Best value: 3.3287:  50%|█████     | 25/50 [55:41<35:29, 85.19s/it]

[I 2026-05-06 21:00:36,792] Trial 24 finished with value: 0.930825464725205 and parameters: {'atr_length': 11, 'atr_mult': 2.25, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 140, 'tolerance': 0.05, 'max_depth_pct': 0.3168076086680035, 'min_total_reduction': 0.7451197171226335, 'compression_threshold': 0.9471742643444219, 'vol_contraction_threshold': 0.8877741483452114, 'volume_ratio_threshold': 1.6144840249745405, 'max_gap_days': 22}. Best is trial 6 with value: 3.3286963277018153.

Best trial: 25. Best value: 4.13204:  52%|█████▏    | 26/50 [56:27<29:24, 73.51s/it]

[I 2026-05-06 21:01:23,034] Trial 25 finished with value: 4.132041111347284 and parameters: {'atr_length': 12, 'atr_mult': 3.5, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 120, 'tolerance': 0.05, 'max_depth_pct': 0.32846215580994775, 'min_total_reduction': 0.8602632729686918, 'compression_threshold': 0.8874724117023911, 'vol_contraction_threshold': 0.9263365994864087, 'volume_ratio_threshold': 1.5183214679042045, 'max_gap_days': 37}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  54%|█████▍    | 27/50 [57:47<28:52, 75.32s/it]

[I 2026-05-06 21:02:42,593] Trial 26 finished with value: 2.8732813675136395 and parameters: {'atr_length': 15, 'atr_mult': 3.25, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 130, 'tolerance': 0.05, 'max_depth_pct': 0.34621062574570804, 'min_total_reduction': 0.8953653324680071, 'compression_threshold': 0.8316147957231464, 'vol_contraction_threshold': 0.9385986586450342, 'volume_ratio_threshold': 1.6638001539937706, 'max_gap_days': 31}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  56%|█████▌    | 28/50 [58:46<25:50, 70.49s/it]

[I 2026-05-06 21:03:41,822] Trial 27 finished with value: 3.438206996093768 and parameters: {'atr_length': 12, 'atr_mult': 3.5, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 130, 'tolerance': 0.07500000000000001, 'max_depth_pct': 0.3389148081658599, 'min_total_reduction': 0.8029612323590576, 'compression_threshold': 0.9087977953750126, 'vol_contraction_threshold': 0.9102511582921938, 'volume_ratio_threshold': 1.624424056189143, 'max_gap_days': 38}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  58%|█████▊    | 29/50 [59:24<21:16, 60.78s/it]

[I 2026-05-06 21:04:19,944] Trial 28 finished with value: 0.6561850390526565 and parameters: {'atr_length': 11, 'atr_mult': 3.5, 'min_contractions': 3, 'max_contractions': 6, 'lookback_bars': 110, 'tolerance': 0.07500000000000001, 'max_depth_pct': 0.38036846765396043, 'min_total_reduction': 0.7994483631066645, 'compression_threshold': 0.9083886396278451, 'vol_contraction_threshold': 0.8668989914382654, 'volume_ratio_threshold': 1.808342426310514, 'max_gap_days': 39}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  60%|██████    | 30/50 [1:01:03<24:05, 72.28s/it]

[I 2026-05-06 21:05:59,038] Trial 29 finished with value: 2.0039505116497938 and parameters: {'atr_length': 13, 'atr_mult': 3.0, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 140, 'tolerance': 0.1, 'max_depth_pct': 0.2678941209746183, 'min_total_reduction': 0.7820908503960847, 'compression_threshold': 0.886967184054495, 'vol_contraction_threshold': 0.9167727365689028, 'volume_ratio_threshold': 1.5171051967053233, 'max_gap_days': 39}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  62%|██████▏   | 31/50 [1:01:44<19:51, 62.73s/it]

[I 2026-05-06 21:06:39,482] Trial 30 finished with value: 2.5885377573191644 and parameters: {'atr_length': 11, 'atr_mult': 3.5, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 110, 'tolerance': 0.1, 'max_depth_pct': 0.36169707954440256, 'min_total_reduction': 0.888581688912742, 'compression_threshold': 0.9397791297199962, 'vol_contraction_threshold': 0.8474888830527112, 'volume_ratio_threshold': 1.4394188603671159, 'max_gap_days': 39}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  64%|██████▍   | 32/50 [1:02:39<18:07, 60.44s/it]

[I 2026-05-06 21:07:34,595] Trial 31 finished with value: 3.0657953375190234 and parameters: {'atr_length': 14, 'atr_mult': 3.25, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 110, 'tolerance': 0.05, 'max_depth_pct': 0.3132301756637876, 'min_total_reduction': 0.8500669352659994, 'compression_threshold': 0.917887943498858, 'vol_contraction_threshold': 0.9409969600300815, 'volume_ratio_threshold': 1.555245239153001, 'max_gap_days': 40}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  66%|██████▌   | 33/50 [1:03:15<15:05, 53.25s/it]

[I 2026-05-06 21:08:11,055] Trial 32 finished with value: 2.601786074075884 and parameters: {'atr_length': 21, 'atr_mult': 3.25, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 100, 'tolerance': 0.05, 'max_depth_pct': 0.2844053220900147, 'min_total_reduction': 0.8760965486853745, 'compression_threshold': 0.8334125285442161, 'vol_contraction_threshold': 0.9141340175413768, 'volume_ratio_threshold': 1.444893292025049, 'max_gap_days': 36}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  68%|██████▊   | 34/50 [1:04:22<15:18, 57.42s/it]

[I 2026-05-06 21:09:18,200] Trial 33 finished with value: 2.667120668198431 and parameters: {'atr_length': 13, 'atr_mult': 3.5, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 140, 'tolerance': 0.07500000000000001, 'max_depth_pct': 0.38542813404318843, 'min_total_reduction': 0.7901269923327375, 'compression_threshold': 0.8490901497337655, 'vol_contraction_threshold': 0.9301465841269051, 'volume_ratio_threshold': 1.448472806743497, 'max_gap_days': 35}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  70%|███████   | 35/50 [1:05:33<15:22, 61.48s/it]

[I 2026-05-06 21:10:29,162] Trial 34 finished with value: 1.2398535171151903 and parameters: {'atr_length': 13, 'atr_mult': 3.0, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 120, 'tolerance': 0.07500000000000001, 'max_depth_pct': 0.2987548389618826, 'min_total_reduction': 0.7203951063174852, 'compression_threshold': 0.8931754811483145, 'vol_contraction_threshold': 0.8715435207534241, 'volume_ratio_threshold': 1.3521963174266889, 'max_gap_days': 24}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  72%|███████▏  | 36/50 [1:06:54<15:42, 67.31s/it]

[I 2026-05-06 21:11:50,068] Trial 35 finished with value: 0.14431364132303076 and parameters: {'atr_length': 11, 'atr_mult': 2.75, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 120, 'tolerance': 0.05, 'max_depth_pct': 0.34596141424882787, 'min_total_reduction': 0.6778510749044843, 'compression_threshold': 0.9487048615657258, 'vol_contraction_threshold': 0.8145244496286785, 'volume_ratio_threshold': 1.5207911477480287, 'max_gap_days': 21}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  74%|███████▍  | 37/50 [1:08:05<14:48, 68.33s/it]

[I 2026-05-06 21:13:00,772] Trial 36 finished with value: 2.414862912668037 and parameters: {'atr_length': 13, 'atr_mult': 3.25, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 140, 'tolerance': 0.1, 'max_depth_pct': 0.32053080215366136, 'min_total_reduction': 0.7103515231603611, 'compression_threshold': 0.9266459043697787, 'vol_contraction_threshold': 0.9264848717118302, 'volume_ratio_threshold': 1.6265944437991064, 'max_gap_days': 20}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  76%|███████▌  | 38/50 [1:09:07<13:17, 66.43s/it]

[I 2026-05-06 21:14:02,789] Trial 37 finished with value: 2.831192227925687 and parameters: {'atr_length': 10, 'atr_mult': 3.25, 'min_contractions': 3, 'max_contractions': 6, 'lookback_bars': 120, 'tolerance': 0.05, 'max_depth_pct': 0.35690708196742915, 'min_total_reduction': 0.85173444916131, 'compression_threshold': 0.9058891835310835, 'vol_contraction_threshold': 0.9087853532156427, 'volume_ratio_threshold': 1.3662155917363998, 'max_gap_days': 33}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  78%|███████▊  | 39/50 [1:10:04<11:41, 63.73s/it]

[I 2026-05-06 21:15:00,222] Trial 38 finished with value: 3.2108501427607608 and parameters: {'atr_length': 16, 'atr_mult': 2.5, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 80, 'tolerance': 0.05, 'max_depth_pct': 0.3183806577148242, 'min_total_reduction': 0.7549809506911707, 'compression_threshold': 0.8614087462457723, 'vol_contraction_threshold': 0.9283701258714633, 'volume_ratio_threshold': 1.324920661107036, 'max_gap_days': 39}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  80%|████████  | 40/50 [1:10:21<08:16, 49.65s/it]

[I 2026-05-06 21:15:17,025] Trial 39 finished with value: 3.3558561877424187 and parameters: {'atr_length': 16, 'atr_mult': 3.25, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 80, 'tolerance': 0.07500000000000001, 'max_depth_pct': 0.2552333636561291, 'min_total_reduction': 0.8449241190444939, 'compression_threshold': 0.8965523754316466, 'vol_contraction_threshold': 0.8950313158325826, 'volume_ratio_threshold': 1.3431095917141564, 'max_gap_days': 40}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  82%|████████▏ | 41/50 [1:12:44<11:38, 77.64s/it]

[I 2026-05-06 21:17:39,962] Trial 40 finished with value: 2.5895104262641846 and parameters: {'atr_length': 19, 'atr_mult': 3.0, 'min_contractions': 2, 'max_contractions': 7, 'lookback_bars': 80, 'tolerance': 0.07500000000000001, 'max_depth_pct': 0.2893992577185144, 'min_total_reduction': 0.853380761779615, 'compression_threshold': 0.8860974998005149, 'vol_contraction_threshold': 0.8655250567420067, 'volume_ratio_threshold': 1.4035082629595061, 'max_gap_days': 37}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  84%|████████▍ | 42/50 [1:13:13<08:23, 62.88s/it]

[I 2026-05-06 21:18:08,403] Trial 41 finished with value: 3.0095421754304024 and parameters: {'atr_length': 17, 'atr_mult': 3.25, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 90, 'tolerance': 0.05, 'max_depth_pct': 0.26485035412951957, 'min_total_reduction': 0.8171663766534639, 'compression_threshold': 0.9330104241527708, 'vol_contraction_threshold': 0.9426049453911272, 'volume_ratio_threshold': 1.3162356884362976, 'max_gap_days': 40}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  86%|████████▌ | 43/50 [1:14:33<07:57, 68.17s/it]

[I 2026-05-06 21:19:28,904] Trial 42 finished with value: 1.7539216897419507 and parameters: {'atr_length': 11, 'atr_mult': 3.0, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 130, 'tolerance': 0.07500000000000001, 'max_depth_pct': 0.3140926074784156, 'min_total_reduction': 0.7831330170495531, 'compression_threshold': 0.8796823704987778, 'vol_contraction_threshold': 0.8892121412772845, 'volume_ratio_threshold': 1.8477175807715365, 'max_gap_days': 37}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  88%|████████▊ | 44/50 [1:14:44<05:05, 50.84s/it]

[I 2026-05-06 21:19:39,324] Trial 43 finished with value: 3.309625560922086 and parameters: {'atr_length': 13, 'atr_mult': 3.5, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 80, 'tolerance': 0.05, 'max_depth_pct': 0.27840761337080766, 'min_total_reduction': 0.8422820653224099, 'compression_threshold': 0.9223798351888134, 'vol_contraction_threshold': 0.8417400293057871, 'volume_ratio_threshold': 1.378344876595146, 'max_gap_days': 36}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  90%|█████████ | 45/50 [1:14:54<03:14, 38.84s/it]

[I 2026-05-06 21:19:50,173] Trial 44 finished with value: 2.9079794535946717 and parameters: {'atr_length': 14, 'atr_mult': 3.5, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 80, 'tolerance': 0.05, 'max_depth_pct': 0.30353045474359336, 'min_total_reduction': 0.8852928243935347, 'compression_threshold': 0.9274141417570768, 'vol_contraction_threshold': 0.8533556398992933, 'volume_ratio_threshold': 1.4424193374947611, 'max_gap_days': 34}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  92%|█████████▏| 46/50 [1:15:22<02:22, 35.52s/it]

[I 2026-05-06 21:20:17,932] Trial 45 finished with value: 0.2564250286933568 and parameters: {'atr_length': 16, 'atr_mult': 3.0, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 80, 'tolerance': 0.07500000000000001, 'max_depth_pct': 0.2745836344951919, 'min_total_reduction': 0.7837206699581074, 'compression_threshold': 0.8901679788671047, 'vol_contraction_threshold': 0.8484173157615864, 'volume_ratio_threshold': 1.4023543291081495, 'max_gap_days': 37}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  94%|█████████▍| 47/50 [1:16:05<01:53, 37.83s/it]

[I 2026-05-06 21:21:01,151] Trial 46 finished with value: 2.4991465464116 and parameters: {'atr_length': 11, 'atr_mult': 2.75, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 80, 'tolerance': 0.05, 'max_depth_pct': 0.2507115771775384, 'min_total_reduction': 0.8371908438778476, 'compression_threshold': 0.8556281836155348, 'vol_contraction_threshold': 0.8913915794624451, 'volume_ratio_threshold': 1.3775987610156795, 'max_gap_days': 38}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  96%|█████████▌| 48/50 [1:16:58<01:24, 42.39s/it]

[I 2026-05-06 21:21:54,181] Trial 47 finished with value: 1.8769701055556758 and parameters: {'atr_length': 17, 'atr_mult': 3.5, 'min_contractions': 3, 'max_contractions': 6, 'lookback_bars': 130, 'tolerance': 0.05, 'max_depth_pct': 0.3172691108948708, 'min_total_reduction': 0.7687184923349493, 'compression_threshold': 0.9393066171461523, 'vol_contraction_threshold': 0.940926275783861, 'volume_ratio_threshold': 1.7641453489448757, 'max_gap_days': 36}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204:  98%|█████████▊| 49/50 [1:18:02<00:48, 48.75s/it]

[I 2026-05-06 21:22:57,760] Trial 48 finished with value: 2.071255031163409 and parameters: {'atr_length': 15, 'atr_mult': 3.5, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 130, 'tolerance': 0.1, 'max_depth_pct': 0.3569670311402051, 'min_total_reduction': 0.8475507492840639, 'compression_threshold': 0.8829218314597391, 'vol_contraction_threshold': 0.8906859563565565, 'volume_ratio_threshold': 1.6014173283206738, 'max_gap_days': 40}. Best is trial 25 with value: 4.132041111347284.

Best trial: 25. Best value: 4.13204: 100%|██████████| 50/50 [1:18:57<00:00, 94.74s/it]

[I 2026-05-06 21:23:52,419] Trial 49 finished with value: 2.867067152312463 and parameters: {'atr_length': 13, 'atr_mult': 3.5, 'min_contractions': 3, 'max_contractions': 7, 'lookback_bars': 140, 'tolerance': 0.05, 'max_depth_pct': 0.3140641683570618, 'min_total_reduction': 0.7173674459334882, 'compression_threshold': 0.8696495952820884, 'vol_contraction_threshold': 0.8939627132888232, 'volume_ratio_threshold': 1.420865459428848, 'max_gap_days': 20}. Best is trial 25 with value: 4.132041111347284.

Optimización completada: 50 trials
Best score: +4.1320 (trial #25)
Cache stats: {'hits': 252, 'misses': 648, 'hit_rate': 0.28, 'size': 648}

## 5. Inspeccionar resultados

### 5a. Best trial

In [10]:
best = study.best_trial
print(f"Best trial: #{best.number}")
print(f"  score:         {best.value:+.4f}")
print(f"  n_trades:      {best.user_attrs['n_trades']}")
print(f"  expectancy_r:  {best.user_attrs['expectancy_r']:+.4f}")
print(f"  win_rate:      {best.user_attrs['win_rate']:.1%}")
print(f"  profit_factor: {best.user_attrs['profit_factor']:.2f}")
print(f"\nParams:")
for k, v in sorted(best.params.items()):
    print(f"  {k}: {v}")

Best trial: #25
  score:         +4.1320
  n_trades:      26
  expectancy_r:  +0.8104
  win_rate:      50.0%
  profit_factor: 3.40

Params:
  atr_length: 12
  atr_mult: 3.5
  compression_threshold: 0.8874724117023911
  lookback_bars: 120
  max_contractions: 7
  max_depth_pct: 0.32846215580994775
  max_gap_days: 37
  min_contractions: 3
  min_total_reduction: 0.8602632729686918
  tolerance: 0.05
  vol_contraction_threshold: 0.9263365994864087
  volume_ratio_threshold: 1.5183214679042045

### 5b. Top 10 trials

In [11]:
top10 = top_trials_summary(study, n=10)
display(top10)

,trial_number,score,n_trades,expectancy_r,win_rate,profit_factor,atr_length,atr_mult,min_contractions,max_contractions,lookback_bars,tolerance,max_depth_pct,min_total_reduction,compression_threshold,vol_contraction_threshold,volume_ratio_threshold,max_gap_days
0,25,4.1320,26,0.8104,0.5000,3.4008,12,3.5000,3,7,120,0.0500,0.3285,0.8603,0.8875,0.9263,1.5183,37
1,27,3.4382,29,0.6385,0.4483,2.6930,12,3.5000,3,7,130,0.0750,0.3389,0.8030,0.9088,0.9103,1.6244,38
2,39,3.3559,12,0.9688,0.5833,4.4905,16,3.2500,3,7,80,0.0750,0.2552,0.8449,0.8966,0.8950,1.3431,40
3,6,3.3287,43,0.5076,0.4419,2.5648,10,3.2500,3,7,130,0.0500,0.3217,0.6790,0.9158,0.8747,1.5316,21
4,43,3.3096,8,1.3082,0.6250,9.2185,13,3.5000,3,7,80,0.0500,0.2784,0.8423,0.9224,0.8417,1.3783,36
5,21,3.2885,17,0.7976,0.5294,5.3068,15,3.2500,3,7,90,0.0500,0.2931,0.8559,0.8903,0.9451,1.3912,40
6,38,3.2109,41,0.5015,0.5122,2.2702,16,2.5000,3,7,80,0.0500,0.3184,0.7550,0.8614,0.9284,1.3249,39
7,20,3.1527,16,0.7882,0.5625,4.5021,15,3.0000,3,6,80,0.1000,0.3112,0.8431,0.8670,0.9178,1.4660,40
8,31,3.0658,30,0.5597,0.4667,2.4422,14,3.2500,3,7,110,0.0500,0.3132,0.8501,0.9179,0.9410,1.5552,40
9,0,3.0531,16,0.7633,0.4375,3.8732,15,3.5000,3,6,90,0.0750,0.2616,0.8665,0.8503,0.8916,1.3144,40

### 5c. Importancia de parámetros (fANOVA)

In [12]:
imp = param_importance(study)
if imp is not None:
    display(imp)
else:
    print("param_importance no pudo calcularse (pocos trials o error de fANOVA)")

                        param  importance
0   vol_contraction_threshold      0.2082
1                max_gap_days      0.1732
2      volume_ratio_threshold      0.1576
3         min_total_reduction      0.1442
4               max_depth_pct      0.1333
5                    atr_mult      0.0527
6       compression_threshold      0.0484
7               lookback_bars      0.0240
8            min_contractions      0.0202
9                  atr_length      0.0146
10           max_contractions      0.0120
11                  tolerance      0.0118

### 5d. Visualizaciones de Optuna

In [13]:
try:
    from optuna.visualization import (
        plot_optimization_history,
        plot_parallel_coordinate,
        plot_param_importances,
        plot_slice,
    )
    HAS_PLOTLY = True
except ImportError:
    HAS_PLOTLY = False
    print("plotly no instalado. Correr: pip install plotly")

In [14]:
if HAS_PLOTLY:
    fig = plot_optimization_history(study)
    fig.update_layout(title="Optimization History", height=400)
    fig.show()

In [15]:
if HAS_PLOTLY:
    fig = plot_parallel_coordinate(
        study,
        params=[
            "atr_mult", "tolerance", "max_depth_pct",
            "compression_threshold", "vol_contraction_threshold",
            "volume_ratio_threshold",
        ],
    )
    fig.update_layout(title="Parallel Coordinate (top params)", height=500)
    fig.show()

In [16]:
if HAS_PLOTLY:
    try:
        fig = plot_param_importances(study)
        fig.update_layout(title="Parameter Importances (fANOVA)", height=400)
        fig.show()
    except Exception as e:
        print(f"plot_param_importances falló: {e}")

In [17]:
if HAS_PLOTLY:
    fig = plot_slice(
        study,
        params=["atr_mult", "tolerance", "compression_threshold", "volume_ratio_threshold"],
    )
    fig.update_layout(title="Slice Plot (key params vs score)", height=400)
    fig.show()

## 6. Re-ejecutar best trial para validar reproducibilidad

In [18]:
best_params = reconstruct_pipeline_params(study.best_trial.params)
rerun_result = run_backtest_for_params(universe, best_params)
rerun_metrics = rerun_result["metrics"]
rerun_score = compute_objective_score(rerun_metrics)

original_score = study.best_value
score_diff = abs(rerun_score - original_score)

print(f"Score original:    {original_score:+.6f}")
print(f"Score re-run:      {rerun_score:+.6f}")
print(f"Diferencia:        {score_diff:.2e}")

if score_diff > 1e-6:
    print("\n⚠ WARNING: scores difieren. Posible floating point o non-determinism.")
    print(f"  Original n_trades: {study.best_trial.user_attrs['n_trades']}")
    print(f"  Re-run n_trades:   {rerun_metrics['n_trades']}")
else:
    print("\nReproducibilidad OK: scores idénticos.")

Score original:    +4.132041
Score re-run:      +4.132041
Diferencia:        0.00e+00

Reproducibilidad OK: scores idénticos.

In [19]:
best_trades_df = trades_to_dataframe(rerun_result["all_trades"])
print(f"Trades del best trial: {len(best_trades_df)}")
display(best_trades_df)

Trades del best trial: 26

,trade_num,ticker,entry_date,exit_date,exit_reason,duration_days,entry_price,exit_price,pnl_pct,r_multiple,max_r,n_contractions,stop_method,stop_distance_pct
0,1,AAPL,2016-07-27,2016-09-08,distribution,43,25.7375,26.3800,0.0250,0.3936,1.0000,3,pattern,0.0634
1,2,AAPL,2016-09-08,2016-09-09,distribution,1,26.3800,25.7825,-0.0226,-0.3236,0.0000,3,fixed_pct,0.0700
2,3,AAPL,2024-12-20,2025-01-13,stop_loss,24,254.4900,234.4000,-0.0789,-1.1277,0.2543,3,fixed_pct,0.0700
3,4,AMZN,2017-04-04,2017-06-09,distribution,66,45.3415,48.9155,0.0788,1.1261,1.6464,3,fixed_pct,0.0700
4,5,AMZN,2017-10-27,2017-12-04,distribution,38,55.0475,56.6975,0.0300,0.4282,1.2311,3,fixed_pct,0.0700
5,6,AVGO,2016-06-03,2016-06-24,stop_loss,21,16.2560,14.8720,-0.0851,-1.2163,0.2004,3,fixed_pct,0.0700
6,7,AVGO,2024-12-13,2025-01-27,stop_loss,45,224.8000,202.1300,-0.1008,-1.4406,1.6014,3,fixed_pct,0.0700
7,8,AVGO,2025-01-27,2025-01-28,distribution,1,202.1300,207.3600,0.0259,0.3696,0.3696,3,fixed_pct,0.0700
8,9,BRK.B,2017-09-05,2018-02-05,distribution,153,176.9800,196.8000,0.1120,1.9168,3.8946,3,pattern,0.0584
9,10,GLD,2025-08-29,2026-01-30,trailing_stop,154,318.0700,444.9500,0.3989,7.4134,10.3903,3,pattern,0.0538
10,11,GOOGL,2019-04-29,2019-04-30,stop_loss,1,64.8100,59.9480,-0.0750,-1.0717,0.0000,3,fixed_pct,0.0700
11,12,IWM,2020-10-08,2021-02-25,distribution,140,161.8600,218.6100,0.3506,5.0087,5.8710,3,fixed_pct,0.0700
12,13,JPM,2020-11-09,2020-12-18,distribution,39,116.9000,119.0800,0.0186,0.2664,0.7846,3,fixed_pct,0.0700
13,14,JPM,2020-12-18,2021-06-14,distribution,178,119.0800,157.5700,0.3232,4.6175,5.6817,3,fixed_pct,0.0700
14,15,NVDA,2024-01-08,2024-04-19,trailing_stop,102,52.2530,76.2000,0.4583,6.5470,11.6874,3,fixed_pct,0.0700
15,16,QLD,2017-10-27,2017-11-29,distribution,33,8.6500,8.9413,0.0337,0.5420,1.1325,3,pattern,0.0621
16,17,QQQ,2017-10-27,2017-11-29,distribution,33,151.2400,153.8600,0.0173,0.5336,1.0896,3,pattern,0.0325
17,18,SLV,2023-07-26,2023-08-07,stop_loss,12,22.9100,21.2100,-0.0742,-1.0600,0.0000,3,fixed_pct,0.0700
18,19,SLV,2025-03-13,2025-04-03,distribution,21,30.7400,28.8900,-0.0602,-0.8597,0.2695,3,fixed_pct,0.0700
19,20,TIL,2016-11-15,2017-01-23,distribution,69,84.8000,81.6000,-0.0377,-0.5391,0.4508,3,fixed_pct,0.0700
20,21,TLT,2016-06-27,2016-08-26,distribution,60,139.1700,138.3600,-0.0058,-0.1142,0.6248,3,pattern,0.0509
21,22,TLT,2016-08-26,2016-09-08,distribution,13,138.3600,137.7900,-0.0041,-0.0908,0.2946,3,pattern,0.0454
22,23,TLT,2017-06-02,2017-10-20,distribution,140,125.6200,123.9800,-0.0131,-0.2872,0.6410,3,pattern,0.0455
23,24,TLT,2020-01-30,2020-03-18,trailing_stop,48,144.5800,144.3500,-0.0016,-0.0250,2.9033,4,pattern,0.0636
24,25,TLT,2025-09-05,2026-01-20,distribution,137,88.5600,86.6500,-0.0216,-0.6201,1.1364,3,pattern,0.0348
25,26,TQQQ,2017-10-27,2017-11-29,distribution,33,5.3200,5.5742,0.0478,0.6826,1.4938,3,fixed_pct,0.0700

## 7. Tabla comparativa: baseline vs best Optuna

In [20]:
comparison = pd.DataFrame({
    "Baseline (original)": {
        "score": baseline_score,
        "n_trades": baseline_metrics["n_trades"],
        "expectancy_r": baseline_metrics["expectancy_r"],
        "win_rate": baseline_metrics["win_rate"],
        "profit_factor": baseline_metrics["profit_factor"],
        "avg_winner_r": baseline_metrics["avg_winner_r"],
        "avg_loser_r": baseline_metrics["avg_loser_r"],
    },
    "Best Optuna": {
        "score": rerun_score,
        "n_trades": rerun_metrics["n_trades"],
        "expectancy_r": rerun_metrics["expectancy_r"],
        "win_rate": rerun_metrics["win_rate"],
        "profit_factor": rerun_metrics["profit_factor"],
        "avg_winner_r": rerun_metrics["avg_winner_r"],
        "avg_loser_r": rerun_metrics["avg_loser_r"],
    },
}).T

display(comparison)

,score,n_trades,expectancy_r,win_rate,profit_factor,avg_winner_r,avg_loser_r
Baseline (original),2.7004,78.0000,0.3058,0.4615,1.6237,1.7247,-0.9105
Best Optuna,4.1320,26.0000,0.8104,0.5000,3.4008,2.2958,-0.6751

In [21]:
print("=== Parámetros del baseline vs best Optuna ===")
print(f"{'Parámetro':<30} {'Baseline':>12} {'Optuna':>12}")
print("-" * 56)

baseline_flat = {
    "atr_length": 14, "atr_mult": 2.0,
    "min_contractions": 2, "max_contractions": 6,
    "lookback_bars": 126, "tolerance": 0.10,
    "max_depth_pct": 0.35, "min_total_reduction": 0.80,
    "compression_threshold": 0.85, "vol_contraction_threshold": 0.85,
    "volume_ratio_threshold": 1.5, "max_gap_days": 30,
}
optuna_flat = study.best_trial.params

for k in baseline_flat:
    bval = baseline_flat[k]
    oval = optuna_flat.get(k, "N/A")
    if isinstance(bval, float):
        print(f"{k:<30} {bval:>12.4f} {oval:>12.4f}")
    else:
        print(f"{k:<30} {bval:>12} {oval:>12}")

=== Parámetros del baseline vs best Optuna ===
Parámetro                          Baseline       Optuna
--------------------------------------------------------
atr_length                               14           12
atr_mult                             2.0000       3.5000
min_contractions                          2            3
max_contractions                          6            7
lookback_bars                           126          120
tolerance                            0.1000       0.0500
max_depth_pct                        0.3500       0.3285
min_total_reduction                  0.8000       0.8603
compression_threshold                0.8500       0.8875
vol_contraction_threshold            0.8500       0.9263
volume_ratio_threshold               1.5000       1.5183
max_gap_days                             30           37

## 8. Distribución de trades por ticker (best trial)

In [22]:
ticker_comparison = []
for ticker in sorted(universe.keys()):
    bl_n = baseline_result["per_ticker"].get(ticker, {}).get("n_trades", 0)
    opt_n = rerun_result["per_ticker"].get(ticker, {}).get("n_trades", 0)
    ticker_comparison.append({"ticker": ticker, "baseline_trades": bl_n, "optuna_trades": opt_n})

tc_df = pd.DataFrame(ticker_comparison).set_index("ticker")
tc_df["diff"] = tc_df["optuna_trades"] - tc_df["baseline_trades"]
display(tc_df)
print(f"\nBaseline total: {tc_df['baseline_trades'].sum()}")
print(f"Optuna total:   {tc_df['optuna_trades'].sum()}")

        baseline_trades  optuna_trades  diff
ticker
AAPL                  6              3    -3
AMZN                 14              2   -12
AVGO                  6              3    -3
BRK.B                 3              1    -2
GLD                   4              1    -3
GOOGL                10              1    -9
IWM                   2              1    -1
JPM                   6              2    -4
MSFT                  5              0    -5
NVDA                  2              1    -1
QLD                   2              1    -1
QQQ                   2              1    -1
SLV                   4              2    -2
SPY                   4              0    -4
SQQQ                  2              0    -2
TIL                   1              1     0
TLT                   3              5     2
TQQQ                  2              1    -1

Baseline total: 78
Optuna total:   26

## 9. Todos los trials (DataFrame completo)

In [23]:
all_trials_df = study_to_dataframe(study)
print(f"Total trials: {len(all_trials_df)}")
print(f"Trials con score > 0: {(all_trials_df['score'] > 0).sum()}")
print(f"Trials con n_trades == 0: {(all_trials_df['n_trades'] == 0).sum()}")
print(f"Trials con n_trades >= 10: {(all_trials_df['n_trades'] >= 10).sum()}")
display(all_trials_df.head(20))

Total trials: 50
Trials con score > 0: 48
Trials con n_trades == 0: 0
Trials con n_trades >= 10: 44

,trial_number,score,state,atr_length,atr_mult,min_contractions,max_contractions,lookback_bars,tolerance,max_depth_pct,...,vol_contraction_threshold,volume_ratio_threshold,max_gap_days,n_trades,expectancy_r,win_rate,profit_factor,avg_winner_r,avg_loser_r,trades_per_ticker
0,25,4.1320,COMPLETE,12,3.5000,3,7,120,0.0500,0.3285,...,0.9263,1.5183,37,26,0.8104,0.5000,3.4008,2.2958,-0.6751,"{'AAPL': 3, 'AMZN': 2, 'AVGO': 3, 'BRK.B': 1, ..."
1,27,3.4382,COMPLETE,12,3.5000,3,7,130,0.0750,0.3389,...,0.9103,1.6244,38,29,0.6385,0.4483,2.6930,2.2655,-0.6835,"{'AAPL': 3, 'AMZN': 3, 'AVGO': 3, 'BRK.B': 1, ..."
2,39,3.3559,COMPLETE,16,3.2500,3,7,80,0.0750,0.2552,...,0.8950,1.3431,40,12,0.9688,0.5833,4.4905,2.1365,-0.6661,"{'AAPL': 1, 'AMZN': 2, 'AVGO': 1, 'GLD': 1, 'N..."
3,6,3.3287,COMPLETE,10,3.2500,3,7,130,0.0500,0.3217,...,0.8747,1.5316,21,43,0.5076,0.4419,2.5648,1.8830,-0.5812,"{'AAPL': 3, 'AMZN': 3, 'AVGO': 5, 'BRK.B': 5, ..."
4,43,3.3096,COMPLETE,13,3.5000,3,7,80,0.0500,0.2784,...,0.8417,1.3783,36,8,1.3082,0.6250,9.2185,2.3479,-0.4245,"{'AAPL': 1, 'AMZN': 2, 'GLD': 2, 'TIL': 1, 'TL..."
5,21,3.2885,COMPLETE,15,3.2500,3,7,90,0.0500,0.2931,...,0.9451,1.3912,40,17,0.7976,0.5294,5.3068,1.8563,-0.3935,"{'AAPL': 2, 'AMZN': 2, 'AVGO': 1, 'BRK.B': 1, ..."
6,38,3.2109,COMPLETE,16,2.5000,3,7,80,0.0500,0.3184,...,0.9284,1.3249,39,41,0.5015,0.5122,2.2702,1.7498,-0.8093,"{'AAPL': 2, 'AMZN': 10, 'GLD': 2, 'GOOGL': 3, ..."
7,20,3.1527,COMPLETE,15,3.0000,3,6,80,0.1000,0.3112,...,0.9178,1.4660,40,16,0.7882,0.5625,4.5021,1.8013,-0.5144,"{'AAPL': 1, 'AMZN': 3, 'AVGO': 1, 'GLD': 1, 'I..."
8,31,3.0658,COMPLETE,14,3.2500,3,7,110,0.0500,0.3132,...,0.9410,1.5552,40,30,0.5597,0.4667,2.4422,2.0311,-0.7277,"{'AAPL': 4, 'AMZN': 4, 'AVGO': 3, 'BRK.B': 1, ..."
9,0,3.0531,COMPLETE,15,3.5000,3,6,90,0.0750,0.2616,...,0.8916,1.3144,40,16,0.7633,0.4375,3.8732,2.3518,-0.4723,"{'AAPL': 2, 'AMZN': 1, 'BRK.B': 3, 'GLD': 2, '..."
10,41,3.0095,COMPLETE,17,3.2500,3,7,90,0.0500,0.2649,...,0.9426,1.3162,40,28,0.5688,0.5357,3.7048,1.4542,-0.4529,"{'AAPL': 4, 'AMZN': 2, 'AVGO': 2, 'BRK.B': 4, ..."
11,44,2.9080,COMPLETE,14,3.5000,3,7,80,0.0500,0.3035,...,0.8534,1.4424,34,8,1.1495,0.5000,5.9382,2.7645,-0.4655,"{'AAPL': 1, 'AMZN': 1, 'GLD': 2, 'TIL': 1, 'TL..."
12,26,2.8733,COMPLETE,15,3.2500,3,7,130,0.0500,0.3462,...,0.9386,1.6638,31,24,0.5865,0.3333,2.4475,2.9751,-0.6078,"{'AAPL': 4, 'AMZN': 2, 'AVGO': 1, 'BRK.B': 1, ..."
13,49,2.8671,COMPLETE,13,3.5000,3,7,140,0.0500,0.3141,...,0.8940,1.4209,20,39,0.4591,0.4103,2.1702,2.0754,-0.6653,"{'AAPL': 4, 'AMZN': 5, 'AVGO': 4, 'GLD': 1, 'G..."
14,37,2.8312,COMPLETE,10,3.2500,3,6,120,0.0500,0.3569,...,0.9088,1.3662,33,38,0.4593,0.4474,2.3057,1.8129,-0.6365,"{'AAPL': 5, 'AMZN': 2, 'AVGO': 4, 'BRK.B': 4, ..."
15,1,2.7230,COMPLETE,23,1.7500,2,5,100,0.1250,0.3364,...,0.7779,1.5045,27,66,0.3352,0.4545,1.6725,1.8339,-0.9138,"{'AAPL': 6, 'AMZN': 10, 'AVGO': 5, 'BRK.B': 3,..."
16,33,2.6671,COMPLETE,13,3.5000,3,7,140,0.0750,0.3854,...,0.9301,1.4485,35,31,0.4790,0.3871,2.1355,2.3273,-0.6883,"{'AAPL': 4, 'AMZN': 3, 'AVGO': 4, 'GLD': 1, 'G..."
17,32,2.6018,COMPLETE,21,3.2500,3,7,100,0.0500,0.2844,...,0.9141,1.4449,36,16,0.6504,0.3750,2.7406,2.7311,-0.5979,"{'AAPL': 4, 'AMZN': 1, 'AVGO': 1, 'BRK.B': 1, ..."
18,40,2.5895,COMPLETE,19,3.0000,2,7,80,0.0750,0.2894,...,0.8655,1.4035,37,52,0.3591,0.5192,1.9963,1.3858,-0.7497,"{'AAPL': 3, 'AMZN': 8, 'AVGO': 5, 'BRK.B': 2, ..."
19,30,2.5885,COMPLETE,11,3.5000,3,7,110,0.1000,0.3617,...,0.8475,1.4394,39,26,0.5077,0.5385,2.4963,1.5729,-0.7351,"{'AAPL': 3, 'AMZN': 3, 'AVGO': 2, 'GLD': 4, 'G..."

## 10. Conclusiones y próximos pasos

### Resultados
- **Baseline score** vs **Best Optuna score**: ver tabla comparativa arriba.
- Los parámetros que más impactan el score se ven en la tabla de fANOVA importance.
- La distribución de trades por ticker muestra si Optuna concentra señales en pocos tickers o diversifica.

### Limitaciones de esta Fase 1
- **In-sample optimization**: estamos optimizando y evaluando sobre el mismo periodo. No hay validación out-of-sample.
- **Sin walk-forward**: no probamos si los parámetros generalizan a periodos futuros.
- **Solo `method=tolerance`**: no exploramos `robust_trend` ni otros métodos de compresión.
- **50 trials**: con 12 parámetros, TPE necesita más trials para convergir bien (~200-500).

### Próximos pasos (Fase 2)
1. **Walk-forward validation**: dividir el periodo en ventanas train/test y optimizar rolling.
2. **Out-of-sample test**: correr best params sobre los tickers excluidos (COIN, HOOD, PLTR, SOFI).
3. **Más trials**: escalar a 200+ trials para explorar mejor el espacio.
4. **Explorar métodos**: agregar `robust_trend` y `ratio_normalized` al search space.
5. **Multi-objective**: optimizar expectancy y n_trades como objetivos separados (Pareto front).

### MLflow
Para explorar los resultados en detalle:
```bash
cd /home/gdelarosa/proyectos/deteccion-vcp && mlflow ui --backend-store-uri mlruns/
```

In [26]:
from models.configs import ATRZigZagConfig

# Workaround temporal: convertir swing_config de dict a ATRZigZagConfig
# (bug en results.py - reconstruct_pipeline_params devuelve dict pero el cache espera objeto)
best_params = reconstruct_pipeline_params(study.best_trial.params)
if isinstance(best_params["swing_config"], dict):
    best_params["swing_config"] = ATRZigZagConfig(**best_params["swing_config"])

# Lo mismo para baseline_params (es un dict literal, también necesita convertirse)
if isinstance(baseline_params["swing_config"], dict):
    baseline_params["swing_config"] = ATRZigZagConfig(**baseline_params["swing_config"])

print("Re-corriendo baseline y best Optuna (con cache deberia ser rapido)...")
base_result = run_backtest_for_params(universe, baseline_params, cache=cache)
best_result = run_backtest_for_params(universe, best_params, cache=cache)

Re-corriendo baseline y best Optuna (con cache deberia ser rapido)...